services:

  backend-customer:
    image: peter/backend/customercare
    build:
      context: ./Backend.Customer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"
    networks:
      - proxybackend 
    volumes:
     - localDevStorage:/storage

  backend-finance:
    image: peter/backend/finance
    build:
      context: ./Backend.Finance
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - "5002:5002" 
    networks:
      - proxybackend
    volumes:
     - localDevStorage:/storage

  backend.reverseproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CLUSTER_customer=http://backend-customer:5001
      - CLUSTER_finance=http://backend-finance:5002
    ports:
      - "5000:443"
    networks:
      - proxybackend
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  backend.sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - "MSSQL_SA_PASSWORD=2323f23feEWD##3kkKKef"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"

volumes:
  localDevStorage:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: C:\localDevStorage

networks:
  proxybackend:
    name: proxybackend
    driver: bridge  
