version: '3.8'
services:
  backend-customer:
    image: multicontainertest.azurecr.io/peter/backend/customer
    container_name: customer
    build:
      context: ./Backend.Customer
      dockerfile: Dockerfile

  backend-finance:
    image: multicontainertest.azurecr.io/peter/backend/finance
    container_name: finance
    build:
      context: ./Backend.Finance
      dockerfile: Dockerfile

  backend.reverseproxy:
    image: multicontainertest.azurecr.io/peter/backend/reverseproxy
    container_name: reverseproxy
    build:
      context: ./Backend.ReverseProxy
      dockerfile: Dockerfile

