version: '3.8'
services:
  backend-customercare:
    image: multicontainertest.azurecr.io/peter/backend/customer
    container_name: customer
    build:
      context: ./Backend.Customer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  backend-finance:
    image: multicontainertest.azurecr.io/peter/backend/finance
    container_name: finance
    build:
      context: ./Backend.Finance
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

